# Generated by Django 2.1.1 on 2018-09-30 12:09

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Container',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('glassbottle', 'Glass Bottle'), ('plasticbottle', 'Plastic Bottle'), ('box', 'Box')], max_length=50)),
                ('colour', colorfield.fields.ColorField(default='#FF0000', max_length=18)),
            ],
        ),
    ]
