# Generated by Django 2.1.1 on 2018-09-30 12:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containers', '0001_initial'),
        ('products', '0002_products_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='container',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='containers.Container'),
        ),
    ]
