# Generated by Django 2.1.1 on 2018-09-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_model_auta'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='fotka',
            field=models.ImageField(default='brak fotki', upload_to=''),
        ),
    ]
